# Import digits dataset from scikit learn

In [1]:
from sklearn.datasets import load_digits
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
digits=load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
len(digits.feature_names)

64

In [4]:
digits.target_names
len(digits.target)

1797

In [5]:
df=pd.DataFrame(digits.data,columns=digits.feature_names)
df.head()
# len(df)

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_5  pixel_7_6  pixel_7_7
0        0.0        0.0        5.0  ...        0.0        0.0        0.0
1        0.0        0.0        0.0  ...       10.0        0.0        0.0
2        0.0        0.0        0.0  ...       16.0        9.0        0.0
3        0.0        0.0        7.0  ...        9.0        0.0        0.0
4        0.0        0.0        0.0  ...        4.0        0.0        0.0

[5 rows x 64 columns]

In [6]:
df['target']=digits.target
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0        0.0        0.0        5.0  ...        0.0        0.0       0
1        0.0        0.0        0.0  ...        0.0        0.0       1
2        0.0        0.0        0.0  ...        9.0        0.0       2
3        0.0        0.0        7.0  ...        0.0        0.0       3
4        0.0        0.0        0.0  ...        0.0        0.0       4

[5 rows x 65 columns]

In [7]:
df[df.target==1].head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
1         0.0        0.0        0.0  ...        0.0        0.0       1
11        0.0        0.0        0.0  ...        1.0        0.0       1
21        0.0        0.0        0.0  ...        4.0        0.0       1
42        0.0        0.0        0.0  ...        0.0        0.0       1
47        0.0        0.0        0.0  ...        0.0        0.0       1

[5 rows x 65 columns]

In [8]:
df['digit_number']=df.target.apply(lambda x:digits.target_names[x])
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_7  target  digit_number
0        0.0        0.0        5.0  ...        0.0       0             0
1        0.0        0.0        0.0  ...        0.0       1             1
2        0.0        0.0        0.0  ...        0.0       2             2
3        0.0        0.0        7.0  ...        0.0       3             3
4        0.0        0.0        0.0  ...        0.0       4             4

[5 rows x 66 columns]

# Separate features and Labels from dataset

In [9]:
X=df.drop(['target','digit_number'],axis=1)
y=df.target
y=np.array(y)

# Split Dataset into training and test datasets.

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
print(len(X_train))
print(len(X_test))

1437
360


# Feature Scaliing

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# Train the training datasets based on Support_vector classification model

In [12]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

# Predict the test set result

In [13]:
y_predict=classifier.predict(X_test)
comparission=np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1)
#print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))


# Confusion Metrics

In [14]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_predict))

[[27  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  1  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  1]
 [ 0  1  0  0  0  0 43  0  0  0]
 [ 0  0  0  0  1  0  0 38  0  0]
 [ 0  1  1  1  0  0  0  0 36  0]
 [ 0  0  0  1  0  1  0  0  0 39]]


# Accuracy Score

In [15]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_predict)
print('Accuracy of Model is: {:.2f} %'.format(ac*100))

Accuracy of Model is: 97.50 %
