<a href="https://colab.research.google.com/github/rdpambhar/Machine_Learning_Code/blob/main/Machine_Learning_Code/Supervised%20Learning/Classification/Car_Evaluation/Car_Evaluation_Decision_Tree_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Classifier

### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the dataset

In [2]:
with open('car.names') as f:
  print(f.read())

1. Title: Car Evaluation Database

2. Sources:
   (a) Creator: Marko Bohanec
   (b) Donors: Marko Bohanec   (marko.bohanec@ijs.si)
               Blaz Zupan      (blaz.zupan@ijs.si)
   (c) Date: June, 1997

3. Past Usage:

   The hierarchical decision model, from which this dataset is
   derived, was first presented in 

   M. Bohanec and V. Rajkovic: Knowledge acquisition and explanation for
   multi-attribute decision making. In 8th Intl Workshop on Expert
   Systems and their Applications, Avignon, France. pages 59-78, 1988.

   Within machine-learning, this dataset was used for the evaluation
   of HINT (Hierarchy INduction Tool), which was proved to be able to
   completely reconstruct the original hierarchical model. This,
   together with a comparison with C4.5, is presented in

   B. Zupan, M. Bohanec, I. Bratko, J. Demsar: Machine learning by
   function decomposition. ICML-97, Nashville, TN. 1997 (to appear)

4. Relevant Information Paragraph:

   Car Evaluation Database was 

In [3]:
df= pd.read_csv('car.csv')
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

### Label Encoding of Categorical Features

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
  df[i]=le.fit_transform(df[i])
df.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

### Extract features and target value from dataset

In [5]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

### Splitting the dataset into the Training set and Test set

In [6]:
from  sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [7]:
print(y_test)

[2 2 2 2 2 1 2 0 0 2 2 2 0 2 2 0 2 2 0 2 1 0 0 2 2 2 2 2 2 2 1 0 2 0 1 2 2
 2 2 2 2 2 2 2 3 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 0 2 2 2 2 0 2 2 2 2 2 0 0 0
 0 0 2 0 0 2 0 0 0 2 2 2 2 1 2 2 2 0 2 2 2 3 2 0 0 2 2 2 0 2 3 0 2 0 2 2 2
 2 2 0 2 1 0 2 2 2 2 2 3 2 2 2 2 0 1 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 2 0 2
 0 0 0 0 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 0 0 2 0
 2 1 2 2 2 2 0 2 2 2 0 2 1 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 0
 2 3 2 2 2 3 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 1 2 0 2 2 2 2 2 1 0 0 0 0 2 2
 2 0 2 2 0 2 2 3 2 0 2 2 2 0 2 0 2 2 2 2 2 2 2 0 2 2 0 2 3 1 2 2 2 2 2 2 2
 2 2 2 0 2 0 0 1 1 2 0 2 0 2 1 0 2 2 2 2 2 2 2 0 2 2 0 2 0 0 2 2 2 2 0 2 1
 2 1 2 2 2 3 2 2 3 2 0 2 0 2 2 2 2 0 2 2 0 2 2 2 0 2 0 2 0 2 2 1 3 0 0 2 3
 2 2 2 0 2 2 2 0 2 0 1 2 1 2 2 2 0 2 2 2 2 2 2 3 2 2 0 2 2 0 2 0 2 2 3 2 2
 2 2 0 2 2 2 2 2 2 0 0 2 0 2 1 3 2 2 2 3 2 2 0 2 0]


In [8]:
print(X_train.shape)

(1296, 6)


### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [10]:
X_train[0:5]

array([[-1.33945466,  1.38833941,  1.3399952 , -1.22003611, -1.23282188,
         1.24823964],
       [-1.33945466, -1.31194254,  1.3399952 , -1.22003611,  1.22523528,
         0.01333997],
       [ 0.44281766, -1.31194254, -0.45219652,  1.22380747,  1.22523528,
         0.01333997],
       [ 0.44281766, -0.41184856,  1.3399952 , -1.22003611, -0.0037933 ,
         1.24823964],
       [ 0.44281766,  1.38833941,  0.44389934, -1.22003611, -1.23282188,
         0.01333997]])

In [11]:
X_test[:5]

array([[-0.4483185 ,  1.38833941, -1.34829239,  1.22380747, -0.0037933 ,
         1.24823964],
       [ 1.33395382, -1.31194254, -1.34829239,  0.00188568, -1.23282188,
         1.24823964],
       [-1.33945466,  0.48824542, -1.34829239, -1.22003611,  1.22523528,
         0.01333997],
       [ 1.33395382,  0.48824542, -0.45219652, -1.22003611, -1.23282188,
         0.01333997],
       [-0.4483185 ,  0.48824542,  1.3399952 , -1.22003611, -1.23282188,
         0.01333997]])

### Training the Decision Tree Classifier  model on the Training set

In [12]:
from sklearn.tree import DecisionTreeClassifier
cls=DecisionTreeClassifier(criterion='entropy',splitter='best',random_state=0)
cls.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

### Applying Grid Search to find the best model and the best parameters

In [13]:
from sklearn.model_selection import GridSearchCV
parameters=[{'criterion':['gini','entropy']},
            {'splitter':['best','random']}]
gride_search=GridSearchCV(estimator=cls,param_grid=parameters,scoring='accuracy',cv=10)
gride_search.fit(X_train,y_train)
best_accuracy=gride_search.best_score_
best_parameters=gride_search.best_params_
print('Best Accuracy {:.2f} %'.format(best_accuracy*100))
print('Best Parameters :',best_parameters)

Best Accuracy 98.30 %
Best Parameters : {'criterion': 'entropy'}


### Predicting the Test set results

In [14]:
y_predict=cls.predict(X_test)
print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [1 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [2 2]
 [2 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [3 3]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]

### Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[ 92   5   2   0]
 [  0  21   0   0]
 [  0   0 296   0]
 [  1   0   0  15]]


In [16]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

0.9814814814814815
